// Generated by Wrangler by running `wrangler types --env-interface CloudflareEnv env.d.ts`

interface CloudflareEnv {
	NEXT_PUBLIC_API_BASE_URL: "https://cloudrun-service-191083186598.asia-southeast1.run.app";
	ASSETS: Fetcher;
}
