#:schema node_modules/wrangler/config-schema.json
name = "next-go-gcp-terraform-lab"
main = ".open-next/worker.js"

compatibility_date = "2024-12-20"
compatibility_flags = ["nodejs_compat"]

# Assets used for files and cache priming.
assets = { directory = ".open-next/assets", binding = "ASSETS" }

[vars]
NEXT_PUBLIC_API_BASE_URL = "https://cloudrun-service-191083186598.asia-southeast1.run.app"

[observability]
enabled = true
head_sampling_rate = 1 