name: destroy

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: write
  statuses: write

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  TF_VAR_db_password: ${{ secrets.DB_PASSWORD }}

jobs:
  destroy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: "projects/191083186598/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
          service_account: "terraform@${{ secrets.GCP_PROJECT_ID }}.iam.gserviceaccount.com"

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: |
          terraform init 
        working-directory: infra

      - name: Terraform destroy
        run: |
          terraform destroy -auto-approve
        working-directory: infra
